# Disable the default blank line at the start of the prompt
add_newline = false

format = """
$cmd_duration\
$status\
$line_break\
$directory\
$git_branch\
$git_status\
$conda\
$docker_context\
$username\
$hostname\
$jobs\
$fill\
$line_break\
$character\
"""

# ------------------------------------------------------------------------------
# Line 1: Last command duration and exit code
# ------------------------------------------------------------------------------

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration]($style) "
style = "fg:#666666"
show_notifications = false
min_time_to_notify = 15_000

[status]
format = "[$symbol$status:$signal_name]($style)"
symbol = ""
style = "fg:#d70000"
map_symbol = true

# ------------------------------------------------------------------------------
# Line 2: Information (bg:#222222)
# ------------------------------------------------------------------------------

[directory]
format = "[  $path ]($style)"
style = "bg:#222222 fg:#008787"
read_only = "ğŸ”’"
read_only_style = "bg:#222222 fg:#d70000"
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style)"
symbol = ""
style = "bg:#222222 fg:#5f8700"

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "bg:#222222 fg:#d78700"
conflicted = "!"
ahead = ">"
behind = "<"
diverged = "â†•"
up_to_date = ""
untracked = "#"
stashed = "â‰¡"
modified = "*"
staged = "."
renamed = "Â»"
deleted = "-"

[conda]
format = "[$symbol$environment ]($style)"
style = "bg:#222222 fg:#5f875f"
symbol = "c:"
ignore_base = false

[docker_context]
format = "[$symbol ]($style)"
symbol = "ğŸ³ "
style = "bg:#222222 fg:blue"

[username]
show_always = true
format = "[$user ]($style)"
style_user = "bg:#222222 fg:#8787af"
style_root = "bg:#222222 fg:#d70000"

[hostname]
ssh_only = true
ssh_symbol = "ïƒ¬ "
format = "[$ssh_symbol$hostname]($style)"
style = "bg:#222222 fg:#d75f00"

[jobs]
format = "[%$number ]($style)"
style = "bg:#222222 fg:#d700af"

# Fill: fill the rest of the line
[fill]
symbol = " "
style = "bg:#222222"

# ------------------------------------------------------------------------------
# Line 3: Prompt
# ------------------------------------------------------------------------------

[character]
format = "[â¯ ](fg:#666666)"
